server:
  port: 8081
spring:
  application:
    name: zxx-learn-demo
  redis:
    host: 62.234.211.179
    port: 6379
  datasource:
    #    url: jdbc:mysql://localhost:3306/mybaties?useUnicode=true&useSSL=false&allowMultiQueries=true
    url: jdbc:mysql://62.234.211.179:3306/mybaties?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #    远程mysql密码
    password: Zxx1994,.
    #    本地mysql密码
    #    password: zxx1994
    driver-class-name: com.mysql.jdbc.Driver
    type:  com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 100
  servlet:
    multipart:
      max-request-size: '20MB'
      max-file-size: '20MB'
  cloud:
    nacos:
      discovery:
        server-addr: 62.234.211.179:8848
        namespace: 3f8be2eb-b7d6-4de6-b83b-cb66f4abdade
msg:
  #消息处理超时时间s
  timeOut: 30
logging:
  file: logs/log.log
  level.root: warn
  #  pattern:
  #    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %m%n'
  #    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %m%n'
  level.pri.zxx.webdemo.mappers: warn
swagger:
  config:
    pack-location: pri.zxx
    app-name: ${spring.application.name}
    contact: 15282648585
    desc: '学习汇总'
    version: '1.0'